#! /bin/sh

killall sxhkd; sxhkd &
killall dunst; dunst -conf .config/dunst/dunstrc &
#$HOME/.config/dunst/dunst_color.sh &
feh --bg-fill $HOME/Pictures/pink_flowers.jpg &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

."$HOME/.cache/wal/colors.sh"

bspc config normal_border_color "$clolr1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
