#!/bin/bash

checkPath() {
  if [ ! -f $ORIGIMGPATH ]; then
    echo "File not found: "$ORIGIMGPATH
    exit 0
  fi
}
createNewPath() {
  file_type=${ORIGIMGPATH#*.}
  cut_name=${ORIGIMGPATH%%.*}
  file_name=${cut_name#*/}
  file_path=${cut_name%/*}
  added_name=$file_name-dark
  TEMPIMGPATH=$HOME/temp/conv/$added_name.$file_type
  NEWIMGPATH=$file_path/$added_name.$file_type
  
  export NEWIMGPATH TEMPIMGPATH
}
convertImg() {
  echo "Converting Image..."

  if [[ $preview = 1 ]]; then
    path=$TEMPIMGPATH
  else
    path=$NEWIMGPATH
  fi

  if [ ! -d ${path%/*} ]; then
    mkdir -p $HOME/temp/conv/
    echo "  temp path created: $HOME/temp/conv/"
  fi

  if [ -z ${COLOR} ]; then
    COLOR=($(jq -r '.["special"]["background"]' $HOME/.cache/wal/colors.json))
  fi

  if [ ! -f  $path ]; then
    convert $ORIGIMGPATH -fill $COLOR -colorize $DARKPER $path
  else
    if [ $send_it = 1 ]; then
      rm $path
      convert $ORIGIMGPATH -fill $COLOR -colorize $DARKPER $path 
    else
      echo "File already exists: "$path
      echo "Overwrite file [y/n]"
      # rm $path
      # convert $ORIGIMGPATH -fill $COLOR -colorize $DARKPER $path
    fi
  fi
}
previewImg() {
  echo "Opening preview.."
  feh $TEMPIMGPATH --scale-down -auto-zoom --quiet
  echo "Like it or nah... [y/n]"
}
runWal() {
  echo "Running pywal..."
  wal -i $ORIGIMGPATH --backend wal -n -q
}
sendIt() {
  echo "Sending it..."
  feh --bg-fill $HOME/$NEWIMGPATH
  bspc wm -r
}

DARKPER=""
COLOR=""
ORIGIMGPATH=""
NEWIMGPATH=""
TEMPIMGPATH=""
while getopts "i:b:c:d:pws" opt; do
  case $opt in
    i)
      ORIGIMGPATH=$OPTARG
      export ORIGIMGPTH
    ;;
    c)
      COLOR=$OPTARG
      export COLOR
    ;;
    d)
      DARKPER=$OPTARG
      export DARKPER
    ;;
    p)
      preview=1
    ;;
    w)
      run_wal=1
    ;;
    s)
      send_it=1
    ;;
  esac
done

checkPath
createNewPath
convertImg

if [[ $send_it = 1 ]]; then
  runWal
  sendIt
  run_wal=0
fi
if [[ $preview = 1 ]]; then
  previewImg
fi
if [[ $run_wal = 1 ]]; then
  runWal
fi
