#!/bin/bash

if [ $1 == 'up' ]
then
  brightnessctl --device='smc::kbd_backlight' set +10%
  keyBrightnessPercentage=$(brightnessctl -m -d 'smc::kbd_backlight' | awk -F, '{print substr($4, 0, length($4)-1)}')
 dunstify $keyBrightnessPercentage -r 666
elif [ $1 == 'down' ]
then
  brightnessctl --device='smc::kbd_backlight' set 10%-
  keyBrightnessPercentage=$(brightnessctl -m -d 'smc::kbd_backlight' | awk -F, '{print substr($4, 0, length($4)-1)}')
  dunstify $keyBrightnessPercentage -r 666
else
  dunstify 'else'
fi
#brightnessctl --device='smc::kbd_backlight' set +10%
#keyBrightnessPercentage=$(brightnessctl -m -d 'smc::kbd_backlight' | awk -F, '{print substr($4, 0, length($4)-1)}')


